
variables:
  DEFAULT_BRANCH: msft-main
  RUST_VERSION: 1.68.1

resources:
  repositories:
    - repository: igvm-parser
      type: git
      name: LSG/igvm-parser
      ref: refs/heads/main

trigger:
  batch: false
  tags:
    include:
      - v*
  branches:
    include:
      - $(DEFAULT_BRANCH)

pr:
  autoCancel: false
  drafts: false
  branches:
    include:
      - $(DEFAULT_BRANCH)

stages:
  - stage: CLOUD_HYPERVISOR_BUILD
    jobs:
      - job:

        timeoutInMinutes: 30

        strategy:
          matrix:
            'x86_64 cargo build':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build'
            'x86_64 cargo build --no-default-features --features "mshv,kvm"':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm"'
            'x86_64 cargo build --no-default-features --features "mshv,kvm,snp,igvm"':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm,snp,igvm"'
            'x86_64 cargo build --package vhost_user_net':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --package vhost_user_net'
            'x86_64 cargo build --package vhost_user_block':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-2'
              BUILD_CMD: 'cargo build --package vhost_user_block'
            'x86_64 cargo test --lib --bins --workspace --features mshv':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-2'
              BUILD_CMD: 'cargo test --lib --bins --workspace --features mshv'
            'aarch64 cargo build':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
              BUILD_CMD: 'cargo build'
            'aarch64 cargo build --no-default-features --features "mshv,kvm"':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm"'
            'aarch64 cargo build --no-default-features --features "mshv,kvm,snp,igvm"':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm,snp,igvm"'
            'aarch64 cargo build --package vhost_user_net':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
              BUILD_CMD: 'cargo build --package vhost_user_net'
            'aarch64 cargo build --package vhost_user_block':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
              BUILD_CMD: 'cargo build --package vhost_user_block'
            'aarch64 cargo test --lib --bins --workspace --features mshv':
              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
              BUILD_CMD: 'cargo test --lib --bins --workspace --features mshv'
        pool:
          name: $(AGENT_POOL)
        steps:
        - checkout: self
          persistCredentials: true
        - checkout: igvm-parser
          persistCredentials: true
          fetchTags: false
          clean: true
        - template: templates/ubuntu-20.04-build.yml
        - bash: |
            set -e
            set -x

            pushd "$(Agent.BuildDirectory)/s/cloud-hypervisor"
            $(BUILD_CMD) --release
            popd
          displayName: Build
