
variables:
  DEFAULT_BRANCH: msft-main
  RUST_VERSION: 1.68.1

trigger:
  batch: false
  tags:
    include:
      - v*
  branches:
    include:
      - $(DEFAULT_BRANCH)

pr:
  autoCancel: false
  drafts: false
  branches:
    include:
      - $(DEFAULT_BRANCH)

stages:
  - stage:
    jobs:
      - job: CH_BUILD

        timeoutInMinutes: 30

        strategy:
          matrix:
            'x86_64 cargo build':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build'
            'x86_64 cargo build --no-default-features --features "mshv,kvm"':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm"'
            'x86_64 cargo build --no-default-features --features "mshv,kvm,snp,igvm"':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm,snp,igvm"'
            'x86_64 cargo build --package vhost_user_net':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-1'
              BUILD_CMD: 'cargo build --package vhost_user_net'
            'x86_64 cargo build --package vhost_user_block':
              AGENT_POOL: 'lsg-virt-amd64-1es-agent-pool-2'
              BUILD_CMD: 'cargo build --package vhost_user_block'
#            'aarch64 cargo build':
#              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
#              BUILD_CMD: 'cargo build'
#            'aarch64 cargo build --no-default-features --features "mshv,kvm"':
#              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-1'
#              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm"'
#            'aarch64 cargo build --no-default-features --features "mshv,kvm,snp,igvm"':
#              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-1'
#              BUILD_CMD: 'cargo build --no-default-features --features "mshv,kvm,snp,igvm"'
#            'aarch64 cargo build --package vhost_user_net':
#              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
#              BUILD_CMD: 'cargo build --package vhost_user_net'
#            'aarch64 cargo build --package vhost_user_block':
#              AGENT_POOL: 'lsg-virt-aarch64-1es-agent-pool-2'
#              BUILD_CMD: 'cargo build --package vhost_user_block'
        pool:
          name: $(AGENT_POOL)
        steps:
        - checkout: self
          persistCredentials: true
        - template: templates/ubuntu-20.04-build.yml
        - bash: |
            set -e
            set -x

            $(BUILD_CMD) --release
          displayName: Build

      - job: CH_FMT

        timeoutInMinutes: 30
        pool:
          name: lsg-virt-amd64-1es-agent-pool-3

        steps:
        - checkout: self
          persistCredentials: true
        - template: templates/ubuntu-20.04-build.yml
        - bash: |
            set -e
            set -x

            cargo fmt -- --check

        - bash: test -z "$(git status --porcelain)"

